version: "3.8"

services:
  app_grpc:
    build:
      target: dev
    environment:
      - GRPC=true
    ports:
      - 1313:1313
  app_http:
    build:
      target: dev
    ports:
      - 1323:1323
