version: "3.8"

services:
  app_grpc:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c "make dev"
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - type: volume
        source: app_grpc_volume
        target: /app/tmp
      - type: bind
        source: .
        target: /app
    env_file:
      - .env
    environment:
      - GRPC=true
    ports:
      - 1313:1313
  app_http:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c "make dev"
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - type: volume
        source: app_http_volume
        target: /app/tmp
      - type: bind
        source: .
        target: /app
    env_file:
      - .env
    ports:
      - 1323:1323
  postgres:
    image: postgres:11
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  postgres_volume:
  app_http_volume:
  app_grpc_volume: